export enum Icons {
  ArrowDown = 'arrow-down',
  ArrowDownload = 'arrow-download',
  ArrowRight = 'arrow-right',
  Print = 'print',
  Close = 'close',
  External = 'external',
  Upload = 'upload',
  Download = 'download',
  FileUpload = 'file-upload',
  Trash = 'trash',
  Calendar = 'calendar',
  TooltipQuestion = 'tooltip-question',
  Search = 'search',
}
